name: mangasoup_prototype_3
description: The 3rd Rendition of the MangaSoup App

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  dio: ^3.0.10
  dio_cookie_manager: ^1.0.0  #latest version
  cookie_jar: ^1.0.0

  provider: ^4.0.4
  shared_preferences: ^0.5.12+2
  cached_network_image: ^2.3.3
  flutter_platform_widgets: ^0.70.2
  flutter_screenutil: ^3.1.1
  responsive_framework: ^0.0.9
  flutter:
    sdk: flutter
  # For OS-specific directory paths
  path_provider: ^1.3.0
  sqflite:
  path:
  auto_size_text: ^2.1.0
  bot_toast: ^3.0.1
  html:
  intl: ^0.16.1
  photo_view: ^0.10.2
  flutter_local_notifications: ^3.0.1+2
  workmanager: ^0.2.0
  connectivity: ^2.0.1
  image_picker: ^0.6.7+12
  sticky_headers: ^0.1.8+1
  draggable_scrollbar: ^0.0.4
  flutter_downloader: ^1.5.2
  preload_page_view: ^0.1.4









  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
dependency_overrides:
  collection: ^1.14.13
dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - Assets/
    - Assets/More/

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  fonts:
    - family: Lato
      fonts:
        - asset: Assets/Fonts/Lato-Regular.ttf
    - family: Roboto
      fonts:
        - asset: Assets/Fonts/Roboto-Regular.ttf
