name: mangasoup_prototype_3
description: The 3rd Rendition of the MangaSoup App

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.0.1+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  dio: ^4.0.0-beta6
  dio_cookie_manager: ^2.0.0-beta1  #latest version
  cookie_jar: ^3.0.0-beta2

  provider: ^5.0.0
  shared_preferences: ^2.0.3
  cached_network_image: ^3.0.0-nullsafety
  flutter_platform_widgets: ^0.80.0
  flutter_screenutil: ^4.0.3+3
  responsive_framework: ^0.0.9
  url_launcher: ^6.0.2
  flutter:
    sdk: flutter
  # For OS-specific directory paths
  path_provider: ^2.0.1
  sqflite:
  path:
  auto_size_text: ^2.1.0
  bot_toast: ^4.0.0+1
  html:
  intl: ^0.17.0
  photo_view: ^0.11.0
  flutter_local_notifications: ^5.0.0-nullsafety.1
  workmanager:
    git:
      url: https://github.com/ened/flutter_workmanager.git
      ref: 1c4e162ea4e71855856fb9e55a1545b3dae9a25d # flutter 1.20 compatibility
  connectivity: ^3.0.2
  image_picker: ^0.7.2
  preload_page_view: ^0.1.4
  webview_flutter: ^2.0.2
  html_unescape: ^1.0.2
  flutter_launcher_icons: ^0.9.0
  flutter_cache_manager: ^3.0.0-nullsafety.1
  #  scrollable_positioned_list: ^0.1.9
  scrollable_positioned_list:
    git:
      url: https://github.com/mig35/flutter.widgets
      ref: bugfix/173
      path: packages/scrollable_positioned_list
  flutter_rating_bar: ^4.0.0
  cupertino_icons: ^1.0.0
  crypto: ^3.0.0
  percent_indicator: ^2.1.7+2
  visibility_detector: ^0.1.5
  webview_cookie_manager: ^1.0.7

dependency_overrides:
  collection: ^1.14.13
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/

  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
